replicaCount: 1
deploymentStrategy:
  type: Recreate

image:
  repository: netdata/netdata
  tag: "{{ .Chart.AppVersion }}"
  pullPolicy: Always

sd:
  repository: netdata/agent-sd
  tag: v0.2.1
  pullPolicy: Always
  child:
    enabled: true
    configmap:
      name: netdata-child-sd-config-map
      key: config.yml
      # if 'from' is {} the ConfigMap is not generated
      from:
        file: sdconfig/child.yml
        value: {}
    resources: {}
    # limits:
    #  cpu: 50m
    #  memory: 60Mi
    # requests:
    #  cpu: 50m
    #  memory: 60Mi

sysctlImage:
  enabled: false
  repository: alpine
  tag: latest
  pullPolicy: Always
  command: []
  resources: {}

service:
  type: ClusterIP
  port: 19999
  # Use a static loadBalancerIP. Only to be used with type LoadBalancer
  # loadBalancerIP: 10.0.1.69

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - netdata.k8s.local
#  tls:
#    - secretName: netdata-tls
#      hosts:
#        - netdata.k8s.local

rbac:
  create: true
  pspEnabled: true

serviceAccount:
  create: true
  name: netdata


parent:
  resources: {}
    # limits:
    #  cpu: 4
    #  memory: 4096Mi
    # requests:
    #  cpu: 4
    #  memory: 4096Mi

  livenessProbe:
    failureThreshold: 3
    periodSeconds: 30
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    failureThreshold: 3
    periodSeconds: 30
    successThreshold: 1
    timeoutSeconds: 1

  terminationGracePeriodSeconds: 300

  nodeSelector: {}

  tolerations: []

  affinity: {}

  priorityClassName: ""

  env: {}
    # To disable anonymous statistics:
    # DO_NOT_TRACK: 1

  podLabels: {}

  podAnnotations: {}

  database:
    persistence: true
    # Set '-' as the storageclass to get a volume from the default storage class.
    storageclass: "-"
    volumesize: 2Gi

  alarms:
    persistence: true
    # Set '-' as the storageclass to get a volume from the default storage class.
    storageclass: "-"
    volumesize: 100Mi

  configs:
    netdata:
      enabled: true
      path: /etc/netdata/netdata.conf
      data: |
        [global]
          memory mode = save

        [plugins]
          cgroups = yes
          tc = yes
          enable running new plugins = yes
          check for new plugins every = 72000
          python.d = yes
          charts.d = yes
          go.d = yes
          node.d = yes
          apps = yes
          proc = yes
          idlejitter = yes
          diskspace = yes
    stream:
      enabled: true
      path: /etc/netdata/stream.conf
      data: |
        [11111111-2222-3333-4444-555555555555]
          enabled = yes
          history = 3600
          default memory mode = save
          health enabled by default = auto
          allow from = *
    health:
      enabled: true
      path: /etc/netdata/health_alarm_notify.conf
      data: |
        SEND_EMAIL="NO"
        SEND_SLACK="YES"
        SLACK_WEBHOOK_URL=""
        DEFAULT_RECIPIENT_SLACK=""
        role_recipients_slack[sysadmin]="${DEFAULT_RECIPIENT_SLACK}"
        role_recipients_slack[domainadmin]="${DEFAULT_RECIPIENT_SLACK}"
        role_recipients_slack[dba]="${DEFAULT_RECIPIENT_SLACK}"
        role_recipients_slack[webmaster]="${DEFAULT_RECIPIENT_SLACK}"
        role_recipients_slack[proxyadmin]="${DEFAULT_RECIPIENT_SLACK}"
        role_recipients_slack[sitemgr]="${DEFAULT_RECIPIENT_SLACK}"
    exporting:
      enabled: false
      path: /etc/netdata/exporting.conf
      data: ""
    example:
      enabled: false
      path: /etc/netdata/health.d/example.conf
      data: |
        alarm: example_alarm1
          on: example.random
        every: 2s
        warn: $random1 > (($status >= $WARNING)  ? (70) : (80))
        crit: $random1 > (($status == $CRITICAL) ? (80) : (90))
        info: random
          to: sysadmin

  claiming:
    enabled: true
    token: "w9osYUXq-K3ezzKspnLvUUJkxM52oUo2fCvXQK09AxkAST6ZIG4ilhcbUdmTIW5fZgqTsSQ0LRW21lvhNQD1vMtHZmuxZOWYG5J2z5A3WEDwCdy_e9RlHElVumywOZTEgdnkTVw"
    rooms: "fd4be01b-d609-40ee-b929-61c6d6b09723"
    url: "https://app.netdata.cloud"

child:
  enabled: true
  port: "{{ .Values.service.port }}"

  updateStrategy: {}
    # type: RollingUpdate
    # rollingUpdate:
    #   maxUnavailable: 1

  resources: {}
    # limits:
    #  cpu: 4
    #  memory: 4096Mi
    # requests:
    #  cpu: 4
    #  memory: 4096Mi

  livenessProbe:
    failureThreshold: 3
    periodSeconds: 30
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    failureThreshold: 3
    periodSeconds: 30
    successThreshold: 1
    timeoutSeconds: 1

  terminationGracePeriodSeconds: 30

  nodeSelector: {}

  tolerations:
    - operator: Exists
      effect: NoSchedule

  affinity: {}

  priorityClassName: ""

  podLabels: {}

  podAnnotationAppArmor:
    enabled: true

  podAnnotations: {}

  persistUniqueID: true

  configs:
    netdata:
      enabled: true
      path: /etc/netdata/netdata.conf
      data: |
        [global]
          memory mode = none
        [health]
          enabled = no
    stream:
      enabled: true
      path: /etc/netdata/stream.conf
      data: |
        [stream]
          enabled = yes
          destination = netdata:{{ .Values.service.port }}
          api key = 11111111-2222-3333-4444-555555555555
          timeout seconds = 60
          buffer size bytes = 1048576
          reconnect delay seconds = 5
          initial clock resync iterations = 60
    exporting:
      enabled: false
      path: /etc/netdata/exporting.conf
      data: ""
    go.d:
      enabled: true
      path: /etc/netdata/go.d.conf
      data: |
        modules:
          pulsar: no
          prometheus: yes
    kubelet:
      enabled: true
      path: /etc/netdata/go.d/k8s_kubelet.conf
      data: |
        update_every: 1
        autodetection_retry: 0
        jobs:
          - url: http://127.0.0.1:10255/metrics
          - url: https://localhost:10250/metrics
            tls_skip_verify: yes
    kubeproxy:
      enabled: true
      path: /etc/netdata/go.d/k8s_kubeproxy.conf
      data: |
        update_every: 1
        autodetection_retry: 0
        jobs:
          - url: http://127.0.0.1:10249/metrics

  env: {}
    # To disable anonymous statistics:
    # DO_NOT_TRACK: 1
